### ISSUE TITLE
Transition trumps

### ISSUE THREAD

**Issue by tscanlin** [optimizely/oui#144] opened 2015-10-14 01:25 UTC
Hey @tomgenoni @danoc @kwalker3690 what do you guys think about adding a trump (or multiple trumps?) for transitions?

For example, something like:
```
.transition-all--300 {
  @include transition(all 300ms);
}
```

We could maybe have other classes for different timing intervals so that it's easier to standardize them.

This would make it easier to toggle them as well instead of coupling them to other component classes.

Let me know what you all think, I'd be happy to make a PR if you guys think this is a good idea.

**Comment by danoc** [comment] 2015-10-14 13:43
Sort of a duplicate of this PR: https://github.com/optimizely/oui/pull/39

I'm not a fan because I think the ease-of-use will encourage people to go transition-crazy. I think no transition is better than one that is applied solely because it looks cool. 

p13n is a great example of a product where the slide-in transitions look awesome _and_ are necessary because they help the user navigate the single-page app.

I'm curious to hear what @tomgenoni and @kwalker3690 think as well!

**Comment by tscanlin** [comment] 2015-10-14 17:08
So far we have no data to back up the assumption that: "ease-of-use will encourage people to go transition-crazy" because we've never had them before and implementing something like this would be very low risk and easy to change later if it proves to be a problem (we could just remove the rule if it is used improperly).

Totally agree that they should be applied tastefully but I think some consistency would be helpful as well. Right now we are all over the place with transition durations and timing functions.

**Comment by kwalker3690** [comment] 2015-10-14 17:49
Yeah there is the risk of it getting out of hand, but I think if either we don't announce that we've added them to all engineers, or announce them with a clear set of guidelines on when to use them, this can be mitigated. I'm ok with transition trump classes if that's the easiest route to take, but maybe it would be more strategic to have more transition variables that people can grab and use in objects? Or maybe more specific trump classes, like transitioning only background colors or something. I guess I'd be curious of examples/use cases of this, I think transitioning on all could be a bit much in some cases. Could you come up with a quick html template of some examples you'd like to use this on?

**Comment by tomgenoni** [comment] 2015-10-14 18:06
I talked with Jeff about this previously, and he tentatively agreed, that what makes more sense is building transitions into components that have clear use cases. Adding new ones would mean experimenting/prototyping and bringing the examples to the OBA to derive some rules around it. 

@tscanlin you're making my argument by saying "we are all over the place with transition durations and timing functions." Why did that happen? (BTW, it would be a big help if you could do an audit of them and figure out who/how/where we're currently using them.) 

A complicating factor is that different animations require different durations/timing, which strengthens the argument that we ought to bake them into reusable components. I want to avoid Developer A including a transition in one situation but Developer B not including the transition in similar situation in a different part of the app. And of course I can't find it right now but Jeff did build an animated instruction list somewhere in the app. It looks fine but we don't have that transition anywhere else, AFAIK. So there is *some* data that they will be used as one-offs.

**Comment by tscanlin** [comment] 2015-10-14 18:20
@kwalker3690 there is already a transitions mixin that's used in most. But I'm open to having more specific trumps if we think they are necessary, I think 'all' isn't bad to use as long as you are not toggling classes with many properties, otherwise specific transition props are helpful.

+ @nehasaigal1 & @LindaHong since they are the designers that came up with the animations and I'm just trying to help to implement.

Here's the first example:
http://45.56.90.56/dcp-design-prototype/master/#data-layer
Click the "Connect a datasource" button and go through the flow. In this case I think the animations are helpful for the same reasons they help in p13n. They help the user understand where they are in a flow and allow them to navigate through it more easily.

The second example is:
https://optimizely.invisionapp.com/share/7K4IS20S6#/screens/107678808
Where Linda wants the hide / show attributes to animate to convey that the attributes belong the parent datasource.

I guess transition consistency isn't actually the real problem since timing and easing functions are so specific to each use case as you said @tomgenoni. But right now I can build so much using just the classes that we already have (so much so that I barely write css now) and having a transition trump would make implementing the above much easier.

**Comment by tomgenoni** [comment] 2015-10-14 18:50
From a big picture perspective we had been and are still experimenting with animations in p13n. It's been one giant experiment and we've had change/introduce things rapidly and make quick decisions. So if by "we are all over the place" you meant the p13n product, then, yes, that needs to be cleaned up (lots of it does). But the left/right navigation, full screen modals, etc., aren't yet a part of OUI and are components specific to that product. We haven't written clear usage rules around them yet but once the dust settles I'd like to discuss them at the OBA and then create documentation. 

@nehasaigal1 example is a variation of the full-screen sliding navigation that we experimented with but haven't yet used. And I'm not yet sure we should. But that one is an existing component with (somewhat) clear use case: you want to break up disparate forms but orient the user in a larger flow. 

The @LindaHong example is just a variation of `disclose`. So we should be able to build that without much trouble with an existing component, or change disclose and make this example the default. 

But I'm not sure how a transition trump would address either of these? They both require some javascript for various aspects and I'm not sure you want to be transitioning `all` anyway...? 

More importantly I'd say that just because a designer wants to use animation that's not enough reason to build it. Part of what OUI is supposed  to do is empower UI Engs to be collective, thoughtful gatekeepers about what we build. And animations are especially tricky.

**Comment by tscanlin** [comment] 2015-10-14 19:08
You're right that the animation Linda has is definitely very similar to disclose. However, by default disclose doesn't have an animation and there are probably times when you wouldn't want it to be animated. I guess it would just be nice if there was an easy way to have the option of adding one.

But it sounds like you think we should avoid using animations until we have more rules / guidelines.

**Comment by tscanlin** [comment] 2015-10-14 19:31
@jeffz-optimizely do you know what the "animated instruction list" that tom mentioned is?

..it may have been something that I made while trying to do a new take on guiders, but it was never merged into the product..

**Comment by tomgenoni** [comment] 2015-10-14 19:47
What'd I suggest is that for an upcoming OBA we devote a good chunk (or all) of it to animations. Part of the confusion for me is about how much development we'll be doing with A/B vs when it gets ingested into p13n, e.g., should the animations in p13n be applied back into the A/B tool? I'd say no but we can discuss. 

In any case if we can create a list of animations we are doing, and want to do, we can seed a more formal library of animations. That would give designers options to use and make building things out easier and more consistent.

**Comment by tscanlin** [comment] 2015-10-14 19:57
Sounds good to me.

**Comment by danoc** [comment] 2015-10-14 20:14
+1 to everything @tomgenoni said.

We should make sure interested/relevant designers are at the meeting as well.

**Comment by jeffz-optimizely** [comment] 2015-10-14 21:31
@tscanlin I'm not exactly sure what the "animated instruction list" that @tomgenoni mentioned above is, but it may have been some examples I listed of places in the current product where we used animation/transition trumps.

I generally agree with @tomgenoni here. I can see the usefulness of animation/transition trumps, and previously argued for them, but the more I've thought about it, the more I think the best path forward is to build them into the components. The reason trumps were useful in the past is because the product was _not_ well componentized. 

On the point of developers overusing, or misusing, transition trumps, we do have data to suggest they would *not* be overused. The legacy CSS that's in the product now includes the equivalent of transition trumps (see `modules/_transitions.scss`), and that's been there for about 2 years (we lost the git history so I can't see when exactly it was created). They were not overused. A large reason is because most developers didn't know about them. Those that did know about them did not throw them on elements arbitrarily, and pretty much always asked me, or a designer, about animations before coding anything. 

The company is in a different place now, but I don't see why they'd be overused if they existed. The vast majority of things being built include a designer and/or UI engineer, who can be trusted to use them appropriately. Engineers won't be adding transitions to elements willy-nilly without a designer catching it.

Anyway, now that I'm starting to argue against my own point, let me reiterate: I think building them into components is the best path forward. But Tom has final say :)

**Closed** 2015-10-14 21:43 UTC
